version: '3.8'

services:
  # 1. 메시지 브로커 (Spring Boot <-> Python 통신용)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP 포트
      - "15672:15672" # 관리 UI 포트
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=kyle
      - RABBITMQ_DEFAULT_PASS=password

  # 2. 인메모리 캐시 (캐싱용)
  redis:
    image: redis:latest
    container_name: redis-streams
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

  # 3. 지식 그래프 데이터베이스 (Graph RAG용)
  neo4j:
    image: neo4j:latest
    container_name: neo4j-graph
    ports:
      - "7474:7474" # 웹 브라우저 UI 포트
      - "7687:7687" # Bolt 드라이버 통신 포트
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: unless-stopped
    volumes:
      - neo4j-data:/data
  # 4. 에이전트 서비스
  agent:
    build: ./agent
    container_name: ai-agent-api
    ports:
      - "8000:8000"
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - NEO4J_URI=bolt://neo4j:7687
    depends_on:
      - neo4j
      - redis
      - rabbitmq
    restart: unless-stopped

# 컨테이너가 삭제되어도 데이터가 날아가지 않도록 볼륨(저장소)을 매핑합니다.
volumes:
  rabbitmq-data:
  redis-data:
  neo4j-data: